### ISSUE TITLE
Missing wikinotes.utils.courses

### ISSUE THREAD

**Issue by clarle** [dellsystem/wikinotes#1]
In `wikinotes.views.courses`:

```
from wikinotes.utils.courses import get_current_profs, is_already_watching
```

Missing courses.py file in utils leads to borking of entire project.  Also, you really shouldn't import wikinotes.models.courses and wikinotes.utils.courses together anyway.

**Comment by clarle** [comment]
So the reason why your repo works, and no one else's does, is that you have a courses.pyc file that hasn't been deleted from the utils folder.  I fixed the changes in my repo, but I can't send a pull request from a private repo to another private repo.  Just merge mine in sometime.

**Comment by dellsystem** [comment]
lololololol

my bad

good to know

Also, this is no longer a private repository. Make yours public?

**Comment by dellsystem** [comment]
i integrated your changes. Yay for getting to the bottom of the mystery! If you open-source your repository, though, I imagine it would be easier to send a pull request.
