### ISSUE TITLE
Improve unit tests

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#10]
And write them where they are non-existent.

There should also be some fixtures specified specifically for unit testing.

**Comment by clarle** [comment]
Do we have existing tests at the moment? I don't mind writing some, at least it'll help me learn what everything does.

**Comment by dellsystem** [comment]
To do:
- Delete the few existing tests that we have because they're probably outdated anyways
- Write unit tests for all major testable things
- Create a few fixtures for each model (think about how to tackle page fixtures)

**Comment by dellsystem** [comment]
Closing for now, will tackle on a case-by-case basis as necessary.
