### ISSUE TITLE
Check if page has been modified before saving

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#101]
Based on the last commit or the timestamp or whatever

**Comment by dellsystem** [comment]
This shouldn't be necessary any more due to the merge conflict resolution feature.

**Comment by ishyca** [comment]
Hey Wendy, it is Kira, if I want to implement a feature that check who was
editing the lecture and class notes at the same times, which code should I
look into? Also about the uploading image feature, I was not quite sure
which code manage the editing interface and hope you could help me get
started?
