### ISSUE TITLE
Arbitrary header IDs

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#102]
Security vulnerability? Think about it

**Comment by dellsystem** [comment]
Ok yeah it's definitely a problem

**Comment by dellsystem** [comment]
Possible workaround: give all the other elements an ID starting with a capital letter. Doesn't look as nice but gets around the problem.

**Comment by hc5** [comment]
what's the security vulnerability? I can't find any problems other than id collisions

**Comment by dellsystem** [comment]
Not security so much, but ID collisions and undesired behaviour due to
stylesheets and js, yes

**Comment by dellsystem** [comment]
Another possibility: prefix everything with `WN-`. Good enough

**Comment by hc5** [comment]
adding a '-' as postfix would work better i think, adding wn- obfuscates the meaning of the header when taken out of context. also case sensitivity in element id is not universally supported so that can't work at all.

**Comment by hc5** [comment]
nvm adding - looks dumb

**Comment by dellsystem** [comment]
using name instead of id should work
