### ISSUE TITLE
Temporary auto-saving

### ISSUE THREAD

**Issue by hc5** [dellsystem/wikinotes#103]
Consider saving uncommitted edits to a document to localStorage every min/whatever, so if the window is closed unexpectedly the contents are reloaded next time

**Comment by dellsystem** [comment]
Yep, auto-saving is on the feature list. Not sure if saving whether saving it to localStorage or to somewhere else would be better though

**Comment by hc5** [comment]
this should work pretty well
https://github.com/yyyc514/autosave_coffee

**Comment by hc5** [comment]
localStorage has a limit of 5 mb, the css generated by less takes up around 100 kb, a typical page is around 10 kb, 20 kb max. That means it's possible to have up to 200+ autosaved states before localStorage craps out, which seems reasonable
