### ISSUE TITLE
Deployment fabfile.py

### ISSUE THREAD

**Issue by clarle** [dellsystem/wikinotes#106]
I'm writing up the fabfile now.  It follows the standard Django deployment procedure as noted here:

http://www.quora.com/How-do-you-deploy-a-Django-app-using-South-Fabric-Git-and-Virtualenv

Except replacing Apache with Nginx/Gunicorn.

Is the dependencies list updated, or has anything new been added recently that I should know about?

**Comment by hc5** [comment]
the list of dependencies is up-to-date

**Comment by clarle** [comment]
@dellsystem: Why are we bundling python-markdown-mathjax? Is there a specific version that we need to use or did we make some changes to it that require it to be in the directory root? 

If we did make changes to it, we can put it in its own git repo and call pip from there.

**Comment by dellsystem** [comment]
How is this going? Is fabric working well?

> Why are we bundling python-markdown-mathjax? Is there a specific version that we need to use or did we make some changes to it that require it to be in the directory root?

What do you mean? Are you referring to the mdx_mathjax.py file in the root? If so, because all the markdown extensions that either are not included in the standard library or have been modified for our use are bundled in the root directory. I don't see any good alternatives. In any case, I had to modify the extension for compatibility with python-markdown 2.1.0, as it wouldn't work out of the box.

**Comment by clarle** [comment]
Can we move those changes over to another git repository, or is it easier for you to just keep it in this one for now?

You can always do pip install directly from a git repo.  I don't really mind, it just seems a bit messy this way though.

**Comment by dellsystem** [comment]
It is messy, which is annoying, but the mdx_\* files all have to be in the same directory as manage.py or in the markdown extensions directory itself, and it seems silly to require that all the relevant extension files be copied over when this is not necessary. If you can find a good workaround for this that would be cool.

**Comment by hc5** [comment]
I have no idea how to append a commit to an existing issue, but 
https://github.com/hc5/wikinotes/commit/d6dbca3bb96cba2aa13bc85b26d607dd744c738a
fixes the messiness. Now you can make a folder called mdx and put all the mdx_\* files in and it would work
