### ISSUE TITLE
really really really slow main page

### ISSUE THREAD

**Issue by hc5** [dellsystem/wikinotes#108]
When the user is logged in the main page takes way too long to load, generally averaging about 1.1 second in loading time with 1 concurrent request. As it is the main page, having more than a single concurrent request is not unusual and would increase the loading time to an unacceptable degree.

Not sure how to decrease the loading time though, have to think about this

**Comment by dellsystem** [comment]
I'm not surprised. I'll look into this. Thanks for pointing it out

**Comment by dellsystem** [comment]
It's probably because of all the "recent activity" and "your actions" items, lol. Should be better once I put in some form of (un)pagination

**Comment by hc5** [comment]
Seems to me that it's because we're filtering over all the historyitems for all user/courses, twice. Pagination would help marginally but I don't think it's not going to improve much unless we change the way 'watched' courses are being stored.

**Comment by hc5** [comment]
You were right, but the reason is less than obvious.

First I profiled the index() method in main.py, and this is the result I got:

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
51526/11208    0.900    0.000    1.961    0.000 c:\python26\lib\copy.py:144(deepcopy)
      935    0.312    0.000    0.384    0.000 c:\python26\lib\site-packages\django\db\backends\sqlite3\base.py:231(execute)
    50574    0.304    0.000    0.304    0.000 c:\python26\lib\copy.py:261(_keep_alive)
2804/2802    0.198    0.000    2.263    0.001 c:\python26\lib\site-packages\django\db\models\sql\query.py:223(clone)
7489/3740    0.171    0.000    0.999    0.000 c:\python26\lib\copy.py:232(_deepcopy_tuple)
    24408    0.152    0.000    0.152    0.000 c:\python26\lib\encodings\utf_8.py:15(decode)
6550/5604    0.131    0.000    1.074    0.000 c:\python26\lib\site-packages\django\utils\tree.py:55(__deepcopy__)
     2025    0.103    0.000    4.845    0.002 c:\python26\lib\site-packages\django\db\models\fields\related.py:288(__get__)
      935    0.103    0.000    0.198    0.000 c:\python26\lib\site-packages\django\db\models\sql\compiler.py:218(get_default_colum
ns)
```

The thing that's slowing down everything is deepcopy() from copy.py. I'm guessing that deepcopy is used to clone the objects obtained from each query so shenanigans like multiple references to the same object doesn't happen if you make parallel queries. To confirm my suspicions I put a breakpoint on the query line of the code, and stepped in the callstack. And it turns out every time a query is made, `Query.clone()` is called, inside `Query.clone()` there are two calls to `copy.deepcopy()`. Unfortunately, there is no way to avoid making a deepcopy() everytime a query is made, even if the the result is read only, which doesn't require a deepcopy of the queryset. 
By limiting the number of recent activities/actions to 10, the request time of the page drops down to 0.2 seconds, an 80% decrease. Hopefully in the future django supports an option in making read-only queries that avoid deepcopying every object, for now pagination will work fine.

**Comment by dellsystem** [comment]
Transferred to the unpagination issue. See #50 for updates.
