### ISSUE TITLE
watching a course 404's

### ISSUE THREAD

**Issue by hc5** [dellsystem/wikinotes#110]
no idea why. this is on the beta as well so it's not introduced by me

**Comment by hc5** [comment]
WTF????

`course + '/watchs': 'watch',` doesn't 404
`course + '/watc': 'watch',` doesn't 404
`course + '/match': 'watch',` doesn't 404
`course + '/atchs': 'watch',` doesn't 404
`course + '/catch': 'watch',` 404s
`course + '/watch': 'watch',` 404s
`course + '/hatch': 'watch',` 404s
`course + '/hatchs': 'watch',` 404s

**Comment by hc5** [comment]
I have no fucking clue why, but
`course + '\/watch': 'watch',` fixes the issue.

**Comment by hc5** [comment]
this entire issue is a mystery

**Comment by dellsystem** [comment]
Weird, I must have broken something

**Comment by dellsystem** [comment]
Lol, I figured it out. It's stupid. Like, really stupid. My bad. The fact that putting a `\` fixes it is coincidental. I'll change the way I'm mapping URLs to get rid of this issue entirely.

**Comment by hc5** [comment]
why does this happen, i'm curious
