### ISSUE TITLE
Ability to restrict content to McGill students on a per-page basis

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#121]
... which kind of goes against one of our principles, but if it's the only way to keep quality content on the site while avoiding conflict with professors and the administration, then so be it

**Comment by hc5** [comment]
Have a seperate category of users which are 'verified' mcgill users, who can be created by confirmation via a verification email to a mcgill address. Hmm so basically to implement:
- User groups, one for regular users/unauthenticated, and one for verified
  The verification process can be:
- The user clicks verify, a hash based on his ID/Time/salt is generated, and is stored in the db keyed by his userid. This hash is then sent out to the email address(has to be mcgill email)
- The email contains a link which is sends the corresponding user id/hash via GET request to a view. The view looks up the userid in the db and checks the hash against the one which is sent by the GET request
- If everything is correct, add the user to the group
- All pages would have a property which specifies the level of access required, i'm thinking it can either be a linear levels where anyone can view documents with lower levels of access, or it can be like unix permissions. But either way it should be trivial to implement. The page would then 404 or ask for verification if the level of access is not met.

**Comment by dellsystem** [comment]
Closing this because it's a terrible idea and wikinotes was never meant to be MyCourses 2.0
