### ISSUE TITLE
Annoying login behaviour

### ISSUE THREAD

**Issue by tahnok** [dellsystem/wikinotes#126]
Scenario:
If I try to create a new page and I'm not logged in I am directed to either sign up or sign in. If I sign in, I am land at the user control panel instead of being directed to the page I was trying to create

Low priority, but it's a little usability thing

**Comment by dellsystem** [comment]
Good point, that is annoying. I keep forgetting to open an issue about it. I'll work on that now.

**Comment by dellsystem** [comment]
Should work now. Let me know if there are problems with it

**Comment by tahnok** [comment]
You are pretty fast!
