### ISSUE TITLE
Facebook/OpenID authentication and signup

### ISSUE THREAD

**Issue by clarle** [dellsystem/wikinotes#13]
I'd like to do Facebook/OpenID auth and signup as soon as the basic Django auth has been setup.  

We can do it in a few different ways.  Either access each authentication method directly (Facebook is probably the easiest, and will be the one most likely used).  Alternatively, we can use something like:

https://launchpad.net/django-openid-auth

This is probably the best method for doing OpenID with Django.  It's pretty up-to-date (last release is 9/15) so this is definitely usable and integrates well with the default Django auth.

**Comment by dellsystem** [comment]
Being addressed in pull request #19
