### ISSUE TITLE
Move main branch over to wikinotes organization

### ISSUE THREAD

**Issue by clarle** [dellsystem/wikinotes#14]
It'll be a lot easier to have the main branch be the organization repo, and we use our own forks of it as development branches.  Someone obviously will need to keep it updated and merge up new changes every so often.

**Comment by dellsystem** [comment]
Too much effort for now with all the forks. Maybe after the release.

**Comment by dellsystem** [comment]
Reopening to remind myself to create a new development workflow based off the org's repository.
