### ISSUE TITLE
List of recently edited pages in dashboard sidebar is ordered incorrectly

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#146]
reverse order

**Comment by dellsystem** [comment]
Now it doesn't remove duplicates properly

**Comment by hc5** [comment]
silly @dellsystem, you can't use order_by with distinct!

**Comment by dellsystem** [comment]
Every time I think I have a solution I come across a new problem and in the process forget everything I learned the last time I tried to solve it

**Comment by dellsystem** [comment]
I guess I should write a unit test for this
