### ISSUE TITLE
Fix/standardise user profile URLs

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#169]
why can't i get this right

**Comment by ishyca** [comment]
Dear dellsystem, i like how i get lovely email with issue i don't
understand and have no idea how to start fixing.... ;p

So yes, it is completely understandable that you have that reaction,
because i do too.

**Comment by dellsystem** [comment]
ahaha. I didn't realise you got the emails! Are you watching the repository?

**Comment by ishyca** [comment]
Yep, waiting for something small /issue/some free time to  happen
