### ISSUE TITLE
Handle unicode in commit messages

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#188]
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 159: ordinal not in range(128)
```

Seems to be a problem with creating HistoryItem, not with GitPython.
## Steps to reproduce
1. Use a computer that appears to be using a French keyboard layout
2. Attempt to type quotation marks in the commit message when editing a wiki page
3. Resort to googling "quotation mark"
4. Instead of ", use the fancy left and right quotation marks
### Expected result

No error
### Actual result

Error

**Comment by hc5** [comment]
add `# encoding: utf-8` in history.py??

**Comment by dellsystem** [comment]
That's only for unicode literals in the source code afaik, which is not the issue here
