### ISSUE TITLE
Support for other universities

### ISSUE THREAD

**Issue by Glavin001** [dellsystem/wikinotes#212]
- [x] The anti-spam university verification should be easily configurable.
  See https://github.com/dellsystem/wikinotes/blob/a58d99859279aa46fd74634b59b81e6bf169afae/views/main.py#L184

Is there anything else that should be customizable to support other universities?

---

@dellsystem, you mentioned yesterday at McHacks that we should contact you for help on getting setup for other universities. I would like to setup this project for Saint Mary's University in Halifax, Nova Scotia. We also have a Computer Science and Mathematics Society at https://github.com/SMU-CS-and-Math-Society

**Comment by dellsystem** [comment]
Hi @Glavin001! I'm glad you're interested. (Sorry about the previous comment, that wasn't me.) Send me an email (ilostwaldo, gmail) and we'll discuss further :)

**Comment by Glavin001** [comment]
Thanks @dellsystem! I was hoping to take a closer look at the source code this weekend after work, and resolve this issue. Now I will have to find another issue to contribute to :). I am very impressed with wikinotes and excited to start using it at our university. Hopefully it will catch on like it did at McGill.
