### ISSUE TITLE
Pinned courses

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#217]
It would be cool if we could "pin" certain courses to the dashboard, to make it easier to find the courses we're currently taking.

_This issue sponsored by Exam-Driven Development_

**Comment by dellsystem** [comment]
Closed by 885cb5e7c7b9be1326675c412c8efa05bff26c0a (forgot to close from the commit itself, again)

**Comment by dellsystem** [comment]
omg so much better, now I can actually start studying

![wizardry](http://i.imgur.com/NOWq5pQ.png)

**Comment by tlwr** [comment]
howdoi.center?

**Comment by dellsystem** [comment]
whosaysiwanttheminthe.center
