### ISSUE TITLE
Ability to edit title?

### ISSUE THREAD

**Issue by chenglou** [dellsystem/wikinotes#224]
I guess that's not too desirable because it's tied to the URL?

**Comment by dellsystem** [comment]
Haha, this has been an issue for a while (see #69). Unfortunately I haven't gotten around to it. If you need a specific page renamed, let me know and I can take care of it.

**Comment by chenglou** [comment]
I have a looot of pages to rename so I'll just put a note for now. Closing this in favour of #69. Thanks!
