### ISSUE TITLE
Can't register over https

### ISSUE THREAD

**Issue by kanetkarster** [dellsystem/wikinotes#225]
I was trying to register via `https://wikinotes.ca/register/` but got a 403 error.

![screenshot from 2015-01-08 08 43 01](https://cloud.githubusercontent.com/assets/3322724/5663243/65ed66a2-9712-11e4-986c-4ef373deafd2.png)

**Comment by dellsystem** [comment]
Unfortunately wikinotes.ca does not currently support SSL. I suspect the only reason you are able to load the page at all is due to CloudFlare's SSL certificate. Are you able to register through http://wikinotes.ca/register/? And how did you find the https:// link?

Sorry for the inconvenience!

**Comment by dellsystem** [comment]
Just checked CloudFlare and it seems that they've enabled a sort of pseudo SSL support for wikinotes.ca, which might have forced your browser into loading it over https. Just turned it off as that seems like it wreaks havoc with Django's CSRF verification system. Sorry about that, let me know if there are still issues.

**Comment by kanetkarster** [comment]
I'm using the https everywhere addon so it must have been that. Thanks!
