### ISSUE TITLE
Switch to PostgreSQL

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#26]
At least for the BETA.

**Comment by clarle** [comment]
Completed, only code change needed is in settings.py in database settings, but new dependencies now are:
- PostgreSQL 8.4.9 (''apt-get install postgresql''')
- PsycoPG2 ('''apt-get install python-psycopg2''')

**Comment by dellsystem** [comment]
Awesome. Since this is a deployment-specific thing I'll keep the default database as SQLite and mark this as closed.
