### ISSUE TITLE
Deployment script

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#66]
@clarle

Things:
- Minify javascript
- Compile *.less
- Run collectstatic
- Run syncdb (although this won't be able to handle schema migrations)
- Kill and restart gunicorn (although maybe a daemon should take of that)
- virtualenv to isolate the deployment environment

Anything else?

**Comment by clarle** [comment]
Everything here, I plan on adapting this.

https://github.com/flashingpumpkin/django-deploy-essential
