### ISSUE TITLE
Dashboard needs to be designed

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#7]
It should probably have the list of courses a user is watching and the activity on those courses at a minimum, but there should be other stuff too. News items? A queue of edits that have not yet been verified (or "patrolled", in MediaWiki) for users who are flagged as moderators? What else?

If you have layout ideas, you can edit templates/main/dashboard.html and populate it with fake data (as the method for retrieving the list of courses a user is watching has not yet been implemented) or just create a mockup image and post it here as a comment for feedback - up to you.

**Comment by hc5** [comment]
Consider adding a list of pages the user has edited recently, it's really annoying having to find that page everytime. And also sort of off-topic, but automatically watch a course whenever the user creates/edits a document in it?

**Comment by dellsystem** [comment]
Will do @hc5

**Comment by dellsystem** [comment]
Superseded by #133
