### ISSUE TITLE
Misc markdown issues

### ISSUE THREAD

**Issue by hc5** [dellsystem/wikinotes#78]
- if the first line of the text is mathjax, the mathjax div covers over the preview/edit button, disabling them.
- use the sub/superscript extensions?

**Comment by dellsystem** [comment]
- It's supposed to `clear: both;` but [beta.wikinotes.ca](http://beta.wikinotes.ca) isn't doing that for some reason. In any case, it's been fixed, as you can see [here](https://github.com/dellsystem/wikinotes/blob/master/assets/css/wikinotes.less#L302).
- [Subscript](https://github.com/sgraber/markdown.subscript) would be useful. I'll add it to the list of dependencies. Can't find a superscript extension.

**Comment by dellsystem** [comment]
Oh, lol http://github.com/sgraber/markdown.superscript

**Comment by hc5** [comment]
now if the first line is mathjax, it doesn't appear at all

**Comment by dellsystem** [comment]
Closed in 55008032dda6b341222243955a2b2fc800404174, forgot to reference this issue. I'm assuming there's just something wrong with the stylesheet on the beta, as the first issue should not be happening.
