### ISSUE TITLE
Editing a page should not return show()

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#84]
Because it keeps the /edit in the URL and refreshing causes it to re-post. Same for create I think. There should be some sort of submission feedback though.

**Comment by hc5** [comment]
Instead of
   `return show(request, department, number, page_type, term, year, slug)`

do
    `return HttpResponseRedirect(page.get_url())`

instead, for feedback, just do
    `return HttpResponseRedirect(page.get_url()+"?"+status)`

then display a message based on the GET args

**Comment by hc5** [comment]
Or a less messy way that doesn't use GET args,

`return HttpResponseRedirect(page.get_url()+"\success")`

or

`return HttpResponseRedirect(page.get_url()+"\failure")`

Then we map \success and \failure to a view which does call show() with kwargs that tell it to display a success/fail

**Comment by dellsystem** [comment]
Good thinking. Will do.

**Comment by dellsystem** [comment]
Actually, there's no need to redirect upon failure, since failure should result in the same form being shown. I have a different idea

**Comment by hc5** [comment]
the code for failure remains the same because that's the expected behaviour, and the just redirect for success?
