### ISSUE TITLE
Database caching?

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#85]
Not sure if need but [this](http://tech.yipit.com/2011/12/07/django-queryset-caching%E2%80%A6or-how-we-slayed-the-beast-known-as-mysql-joins/) looks cool

**Comment by hc5** [comment]
maybe we can write a unit test to query something from the db 10000 times, then compare the performance. seems easy enough to implement

**Comment by dellsystem** [comment]
Good idea

**Comment by dellsystem** [comment]
Closing for now. Not that important
