### ISSUE TITLE
Ability to highlight the part of the text you want to edit

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#87]
After highlighting, an "edit" button should magically appear. You make your edit (possibly inline? like inline comments on commits here) and it merges with the rest of the document in the natural way.

**Comment by dellsystem** [comment]
Section-editing, not highlight-editing. Should be done through js only

**Comment by dellsystem** [comment]
@dellsystem, please do this soon, because [this](http://beta.wikinotes.ca/MATH_204/summary/winter-2012/course-review) needs to be cleaned up

**Comment by hc5** [comment]
> implying that isn't the most beautiful page on wikinotes

**Comment by dellsystem** [comment]
Please, your tables don't even have colours.

**Comment by dellsystem** [comment]
Bumping to remind myself that this is priority #1

**Comment by dellsystem** [comment]
Addressed by commit 2c611c907a2ffd2930e460000b3e4b7e706699b2. The functionality is pretty basic (some edge cases are ignored, and it's not especially elegant), but it works well enough for most cases and is a lot more robust than I expected.

Things to maybe address one day:
- Tables
- Weirdly-formatted headers (# 1, ### 2, ## 3)
- The other way of doing headers (===, ---)

Things to remember (or, the things I learned throughout my many attempts at solving this problem)
- Can't put it in the TOC extension because TreeProcessors don't get original line number information
- No point in making it a Preprocessor extension because it would do the same thing, but it would be even less elegant (and then we'd have to only enable the extension on the show page) 
- Can't use the regex directly from the fenced code extension because that takes in the entire block (multiple lines including the end)
- No point in making a fallback for people without JS (would have to make it a Markdown extension which doesn't really make sense)
- Sometimes doing it right is less important than just doing it. Why did this take over a year again?

**Comment by dellsystem** [comment]
Reopening so that I can remember to add ajax functionality

**Comment by dellsystem** [comment]
Closing because who needs ajax functionality.
