### ISSUE TITLE
Footnote formatting errors should not result in 500s

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#89]
Seriously

**Comment by hc5** [comment]
wrote up a patch to the footnotes extension that fixes this, replace the footnotes.py in the markdown extensions folder with this:
https://gist.github.com/1462562
should stop 500s from happening

**Comment by dellsystem** [comment]
Awesome. I'll save it as mdx_realfootnotes.py or something so there doesn't have to be any messing about with installed extensions
