### ISSUE TITLE
Consider pre-processing Markdown --> HTML

### ISSUE THREAD

**Issue by dellsystem** [dellsystem/wikinotes#91]
Consider saving it in a field in the database upon save(), rather than having to regenerate the HTML each time. Just think about it. Processor time vs. db size?

**Comment by hc5** [comment]
I can implement this as a markdown extension, then it'll be simple to enable/disable

**Comment by hc5** [comment]
Although i think caching the markdown output will conflict with my idea to cache mathjax.

**Comment by dellsystem** [comment]
It wouldn't be a markdown extension, it would be a call to wikinotes_markdown(). And tell me more about your caching idea tomorrow and we'll see if it does conflict.
